apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: public-ord1
    # Setting a sharing key might save public IP addresses
    # See https://metallb.universe.tf/usage/#ip-address-sharing for more detail
    #metallb.universe.tf/allow-shared-ip: example-1
  name: neox-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: sshd
      port: 22
      targetPort: 22
      protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: neox-0